---
- hosts: fleet
  become: true
  roles:

    #
    # Basics
    - role: system
      tags:
        - system

    - role: 0x0I.systemd
      tags:
        - system

    - role: wakeonlan
      tags:
        - system

    - role: geerlingguy.docker
      tags:
        - docker

    - role: oefenweb.dns
      tags:
        - dns

    - role: geerlingguy.ntp
      tags:
        - ntp

    #
    # Security
    - role: geerlingguy.security
      tags:
        - security

    #
    # SSDs
    - role: stuvusit.smartd
      become: true
      tags:
        - smartd

    #
    # newrelic
    - role: newrelic.newrelic-infra
      become: true
      tags:
        - newrelic
