---
#
# Misc
hostname: "{{ inventory_hostname }}"
timezone: Europe/Berlin
ntp_timezone: "{{ timezone }}"
locale: en_US.UTF-8
keyboard_layout: us
shell: /usr/bin/zsh
docker_dir: /opt/docker/data

#
# Docker
docker_edition: 'ce'
docker_service_state: started
docker_service_enabled: true
docker_install_compose: true
docker_users:
  - "{{ username }}"

#
# Email credentials (for SMART and Snapraid error reporting)
email: taika-nas@e7n.org
email_login: "{{ email }}"
email_smtp_host: smtp.mailbox.org
email_smtp_port: 465
email_smtp_port_startls: 587

## MSMTP
msmtp_default_account: "mailbox"
msmtp_alias_default: "{{ email }}"
msmtp_accounts:
  - account: mailbox
    host: "{{ email_smtp_host }}"
    port: "{{ email_smtp_port_startls }}"
    auth: "on"
    from: "{{ email }}"
    user: "{{ email }}"
    password: "{{ email_password }}"

#
# SMART error reporting
smartd_default_mail_recipients: ["{{ email }}"]
