---
- name: Create gits folder
  file:
    path: "/home/{{ username }}/gits"
    state: directory

- name: Clone the latest dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ username }}/gits/dot"
    recursive: no
    force: yes

- name: Create zsh-plugins folder
  file:
    path: "/home/{{ username }}/.config/zsh-plugins"
    state: directory

- name: Clone zsh-autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "/home/{{ username }}/.config/zsh-plugins/zsh-autosuggestions"
    recursive: no
    force: yes

- name: Clone zsh-syntax-highlighting
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
    dest: "/home/{{ username }}/.config/zsh-plugins/zsh-syntax-highlighting"
    recursive: no
    force: yes

# - name: Move .bashrc to .old
#   become: no
#   command: mv /home/{{ username }}/.bashrc /home/{{ username }}/.bashrc.old

# - name: Move .profile to .old
#   become: no
#   command: mv /home/{{ username }}/.profile /home/{{ username }}/.profile.old

- name: Stow the dotfiles lnx
  become: yes
  shell:
    cmd: stow -d /home/{{ username }}/gits/dot -t /home/{{ username }} lnx
  register: stow_result
  changed_when: stow_result.stdout != ""

- name: Stow the dotfiles nvim
  become: yes
  shell:
    cmd: stow -d /home/{{ username }}/gits/dot -t /home/{{ username }} nvim
  register: stow_result
  changed_when: stow_result.stdout != ""

# do the same for root
- name: Create gits folder
  file:
    path: "/root/gits"
    state: directory

- name: Clone the latest dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "/root/gits/dot"
    recursive: no
    force: yes

- name: Create zsh-plugins folder
  file:
    path: "/root/.config/zsh-plugins"
    state: directory

- name: Clone zsh-autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "/root/.config/zsh-plugins/zsh-autosuggestions"
    recursive: no
    force: yes

- name: Clone zsh-syntax-highlighting
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
    dest: "/root/.config/zsh-plugins/zsh-syntax-highlighting"
    recursive: no
    force: yes

- name: Stow the dotfiles lnx
  become: yes
  shell:
    cmd: stow -d /root/gits/dot -t /root lnx
  register: stow_result
  changed_when: stow_result.stdout != ""

- name: Stow the dotfiles nvim
  become: yes
  shell:
    cmd: stow -d /root/gits/dot -t /root nvim
  register: stow_result
  changed_when: stow_result.stdout != ""
