---
- name: Clone the latest dotfiles repo
  become: yes
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ username }}/dot"
    recursive: no
    force: yes

- name: Create zsh-plugins folder
  become: yes
  file:
    path: "/home/{{ username }}/.config/zsh-plugins"
    state: directory

- name: Clone zsh-autosuggestions
  become: yes
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "/home/{{ username }}/.config/zsh-plugins/zsh-autosuggestions"
    recursive: no
    force: yes

- name: Clone zsh-syntax-highlighting
  become: yes
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
    dest: "/home/{{ username }}/.config/zsh-plugins/zsh-syntax-highlighting"
    recursive: no
    force: yes

# - name: Move .bashrc to .old
#   become: no
#   command: mv /home/{{ username }}/.bashrc /home/{{ username }}/.bashrc.old

# - name: Move .profile to .old
#   become: no
#   command: mv /home/{{ username }}/.profile /home/{{ username }}/.profile.old

- name: Stow the dotfiles
  become: yes
  shell:
    cmd: stow -d /home/{{ username }}/dot -t /home/{{ username }} lnx
  register: stow_result
  changed_when: stow_result.stdout != ""
