---
- name: Clone the latest dotfiles repo
  become: no
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ username }}/dotfiles"
    recursive: no
    force: yes

- name: Stow the dotfiles
  become: no
  shell:
    cmd: stow -v */
    chdir: "/home/{{ username }}/dotfiles"
  register: stow_result
  changed_when: stow_result.stdout != ""
