---
- name: Generate the locale (Debian and Ubuntu)
  become: true
  when: ansible_os_family == 'Debian'
  locale_gen:
    name: "{{ locale }}"
    state: present

- name: Update and upgrade apt packages (Debian and Ubuntu)
  become: true
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    upgrade: true
    autoremove: true
    update_cache: true

- name: Check if reboot required
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  become: true
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install extra packages
  become: true
  ansible.builtin.package:
    name: "{{ extra_packages }}"
    state: present

- name: Set the hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Replace the hostname entry with our own
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: ^127\.0\.0\.1 *localhost
    line: "127.0.0.1 {{ inventory_hostname }}"
    owner: root
    group: root
    mode: '0644'
