---
- name: Set the default shell
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "{{ shell }}"

- name: Set the default shell for root
  become: true
  ansible.builtin.user:
    name: root
    shell: "{{ shell }}"

- name: Set authorized keys taken from url
  ansible.posix.authorized_key:
    user: fng
    state: present
    key: https://github.com/itsfeng.keys

- name: Suppress login messages
  ansible.builtin.file:
    name: "/home/{{ username }}/.hushlogin"
    mode: 0644
    state: touch
    modification_time: preserve
    access_time: preserve
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Disable cron e-mail notifications
  ansible.builtin.cron:
    name: MAILTO
    user: "{{ item }}"
    env: true
    job: ""
  with_items:
    - root
    - "{{ username }}"
