---
- name: Set the name of a sudo group
  set_fact:
    sudo_group: sudo

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group }}'
    line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Copy the public SSH key 
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"
  when: not ansible_check_mode

- name: Set the default shell
  user: 
    name: "{{ username }}"
    shell: "{{ shell }}"

- name: Set the default shell for root
  user: 
    name: "root"
    shell: "{{ shell }}"

- name: Suppress login messages
  file:
    name: /home/{{ username }}/.hushlogin
    mode: 0644
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Disable cron e-mail notifications
  cron:
    name: MAILTO
    user: "{{ item }}"
    env: yes
    job: ""
  with_items:
    - root
    - "{{ username }}"
