---
- name: reload daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: enable wakeonlan unit
  become: true
  ansible.builtin.systemd:
    name: wakeonlan
    enabled: true
